---
- name: 📄 Create a File on All Hosts
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: ✅ Create an empty file (sudarshan.txt)
      file:
        path: /home/ansible/sudarshan.txt
        state: touch
        owner: ansible
        group: ansible
        mode: '0644'
      tags:
        - file
        - create
...
