---
- name: 📦 Install Package Using group_vars Variable
  hosts: all
  become: true
  gather_facts: false

  # 🧾 This playbook uses 'package_name' from group_vars/all.yml
  # Example group_vars/all.yml:
  # package_name: git

  tasks:
    - name: ✅ Install package "{{ package_name }}" from group_vars
      yum:
        name: "{{ package_name }}"
        state: present
      tags:
        - install
        - group-vars
...
